### PR TITLE
Add the ability to specify the local server's listening port.

### LINKED ISSUE #34: Feature Request - Additions to CLI UI
@grant 
Would you be open to adding some stying to the CLI like Firebase CLI? 
_If so, it would be great to be involved!_

image

I have some suggestions using the same NPM packages that are used in the Firebase CLI. 

Firstly is to add something to make the main clasp text stand out using **figlet.js** (possibly something like the images below but other suggestions are welcome): 
clasp-cli

Second is to add some styling to errors and user input with **chalk** and **Inquirer.js**. An example of this might be to ask the user to set a name for otherwise undefined projects or to get them to select deployment versions. Similar to the Firebase CLI and Webpack CLI.

Thanks 👍

### PR DESCRIPTION
**Pull request by chris-garrett**
Fixes #34
- [ X ] `npm run test` succeeds.
- [ X ] `npm run lint` succeeds.
- [ X ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by grant** [comment]
I think this addresses #296?

**Comment by chris-garrett** [comment]
Yes sir

**Comment by grant** [comment]
Thanks for the PR. If we'd like to specify the port for logging in, I'd rather have that as a feature flag than a global environment variable. i.e.

```
clasp login --port 8000
```

This would require modifying these files (as well as others):

- https://github.com/google/clasp/blob/9297b98df6c2c11033319b4e440a1fef0ebc84ee/src/index.ts#L73
- https://github.com/google/clasp/blob/95809d546e699ebb554034353029dda11f6c56f6/src/auth.ts#L161

Some more discussion in the issue would be helpful as well as to how we could implement this.

What do you think?

**Comment by chris-garrett** [comment]
Sounds good to me.

**Comment by grant** [comment]
Closing this PR in favor of a new one that follows `login --port` option:
https://github.com/google/clasp/pull/300#issuecomment-416071380

**Pull request closed without merging**
