### PR TITLE
Updating documentation solving #819

### LINKED ISSUE #819: Support for developing using ES Modules
## Expected Behavior
Documentation describing a setup where one can use ES Modules (import/export-statements)

## Actual Behavior
Currently not in scope

## Steps to Reproduce the Problem

N/A

## Specifications

PR is coming...

### PR DESCRIPTION
**Pull request by atti187**
Fixes #819

- [n/a] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [x] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by contributorpw** [comment]
I think it would be great to specify the entry point of the call to `clasp` or some example workflow when `clasp` is called.

**Comment by atti187** [comment]
@contributorpw - to my understanding, clasp picks every file not being .ignored, so it's business as usual. Nevertheless, I made some clarifications.

**Comment by PopGoesTheWza** [comment]
A detailed practical example would be nice. Maybe something like:
- "we need advanced date manipulation with moment.js"
- retrieve ES module and install it (npm add ?)
- minimal index.ts using moment.js 

Also a paragraph to clarify any limitation about ES Modules which can be "imported"; also the difference with npm (typically commonjs) modules

**Comment by atti187** [comment]
I think that would rather be part of an example repo that could be linked to. I can see if I can set it up.

As for third party dependencies, I'm not sure if and how that'd work with the run-time restrictions of App Scripts - depending on what they're using. Also handling all plugins needed to cope with different module patterns etc is probably out of scope for this PR.

Essentially what this handles is a way to structure your own code.

**Comment by atti187** [comment]
Using moment actually worked with the small test I did! Added a reference to my example repo...

**Comment by atti187** [comment]
Any updates on this? Has anyone tried it out?

**Review by PopGoesTheWza — APPROVED** [review]

**Pull request merged**
