### PR TITLE
fix .clasp.json `filePushOrder`

### LINKED ISSUE #527: the filePushOrder option in not working as documented
Just because the inherited class has a different loading order(alphabetical), it becomes "TypeError: Cannot read property 'prototype' of undefined". [Screen shot](https://github.com/jakenjarvis/clasp-ts-sample/blob/master/IssueSample/Issue01/TypeErrorLine14.png)

I created a sample project to convey this.

## Expected Behavior
case OK:
https://github.com/jakenjarvis/clasp-ts-sample/tree/master/IssueSample/Issue01/ProjectNormal

## Actual Behavior
case NG:
https://github.com/jakenjarvis/clasp-ts-sample/tree/master/IssueSample/Issue01/ProjectAbnormal

TypeError: Cannot read property 'prototype' of undefined (line 14, file "AClass")

## Steps to Reproduce the Problem

1. Swap the class names of AClass and BClass.
2. Oh wonder, it becomes TypeError.

## Specifications

- Windows 10 64bit
- node v10.15.0
- yarn 1.13.0
- @google/clasp 1.6.3
- @types/google-apps-script 0.0.36

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
Fixes #527 

- [ ] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

Successfully tested on a couple of personal projects.
- order of files listed under `filePushOrder` is maintained
- order of files sent through `script.projects.updateContent` is now correct with files listed under `filePushOrder` being first
- if order of files listed under `filePushOrder` is changed, it is properly reflected after issuing a `clasp push`

NB: `npm run test` produces errors but none seems to relate with the changes in this PR

### CODE REVIEW

**Comment by grant** [comment]
Looks good to me. Thanks.

**Comment by grant** [comment]
Note: Master build failed due to exhausted quota.
Should be fine tomorrow.
Not this PR's fault.

Error:
```
AssertionError: expected 'Resource has been exhausted (e.g. check quota).\n' to include 'Request contains an invalid argument.'
```

**Comment by kornthing** [comment]
I'm using clasp 2.3.0 and I don't think that this merge has been fixed athe problem. I've made an example on  [StackOverflow](https://stackoverflow.com/questions/59802430/typescript-classes-order-in-google-appscript-project).
I've listed here all opened issues concerned this problem on Git google/clasp:
- [527](https://github.com/google/clasp/issues/527)
- [718](https://github.com/google/clasp/issues/718)
- [624](https://github.com/google/clasp/issues/624)

**Comment by PopGoesTheWza** [comment]
@kornthing your SO question does not mention using `.clasp.json` and the `filePushOrder` option. Please clarify.

**Pull request merged**
