### PR TITLE
fix: Exit 1 when `clasp run` failed with an error

### PR DESCRIPTION
**Pull request by tricknotes**
Fixes https://github.com/google/clasp/issues/788

- [ ] `npm run test` succeeds.
- [ ] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by tricknotes** [comment]
@googlebot I signed it!

**Comment by PopGoesTheWza** [comment]
@tricknotes can you add test cases for exitCode `0` and `1`?

**Comment by tricknotes** [comment]
@PopGoesTheWza 
Thanks for your review.
Yes, I'll try it 👍 

BTW, I found some untested tests https://github.com/google/clasp/issues/793.
I think test cases against this change will be included in such untested file.

**Comment by tricknotes** [comment]
I changed this PR to draft. I'll change ready when https://github.com/google/clasp/issues/793 is merged.

**Pull request merged**
