### PR TITLE
fixed not working .claspignore

### LINKED ISSUE #587: .claspignore not working at all
## Expected Behavior

The text below written within `.claspignore` is supposed to ignore everything else and select sample.js for push

```
**/**
!sample.js
```

## Actual Behavior
But Alas, after running `clasp status` on the terminal

it did not ignore the rest:
<figure>
'clasp status' on terminal
  <figcaption>"clasp status" on terminal</figcaption>
</figure>
<br><br>
Still did not ignore when i pushed
<figure>
Screen Shot 2019-03-29 at 6 01 52 AM
  <figcaption>"clasp push" on terminal</figcaption>
</figure>

## Steps to Reproduce the Problem

Already given above

## Specifications
- Node version: 10.15.3
- Clasp Version: 2.1.0
- OS: Mac (Mojave)

### PR DESCRIPTION
**Pull request by HeavensBlade**
Fixes #587

### CODE REVIEW

**Comment by campionfellin** [comment]
Can you give a brief example of what files this matches for?

```
ignoreMatches.includes(name.replace(/\//, '\\'))
```

**Comment by HeavensBlade** [comment]
I'm sorry, I just found my fix is not necessary anymore.
In version 2.0.0 using clasp under windows 10 compared the
`ignorematches`: `path/to/file` 
with the `name`: `path\to\file`

Can you [here](https://github.com/google/clasp/releases) mark 2.1.0 as latest release ?
This lead me into thinking there would be no more current version than 2.0.0

**Comment by campionfellin** [comment]
Sure thing! @grant do you want to mark minor versions as releases?

https://github.com/google/clasp/releases/new?tag=2.1.0

**Comment by grant** [comment]
That sounds fine @campionfellin. You should have the ability to create the tag.

You can ping @erickoledadevrel rather than me for publishing since I'm now working on Google. Instructions should be in the [docs/](https://github.com/google/clasp/blob/master/docs/README.md)

**Pull request closed without merging**
