### PR TITLE
Make travis tests

### PR DESCRIPTION
**Pull request by campionfellin**
Starting to write some tests, these gives us ~50% code coverage.

The tests will fail unless you do some setup on the backend:

run `clasp login --ownkey` to generate a `.clasprc.json` file in the directory that Clasp is in. 
```
gem install travis
travis login
travis encrypt-file .clasprc.json --add
```
Now commit the file `.clasprc.json.enc` and '.travis.yml`

Also, on the backend of Travis, set the env variable CLONE_ID to a project that already exists (to test the clone function).

For code coverage (runs after tests) set up the Repo here: https://coveralls.io/

I may be forgetting some steps here, just ping me on Monday if you have any questions.

Signed-off-by: campionfellin <campionfellin@gmail.com>

### CODE REVIEW

**Comment by grant** [comment]
- Added `.clasprc.json.enc`
- Added `CLONE_ID`: [`1IhXK1rXrhkdD_UH4jZ4FnYrnge4xe1Kj5dGYYSQaEjQ1SKahFb7cDWhh`](https://script.google.com/d/1IhXK1rXrhkdD_UH4jZ4FnYrnge4xe1Kj5dGYYSQaEjQ1SKahFb7cDWhh/edit)
- Enabled Coveralls and added badge to README.

**Comment by grant** [comment]
Can we make the test pass locally (on your machine instead of Travis)?

Try to make this PR as small as possible. Maybe we can use nock or just focus on getting >0% coverage for `clasp help`.

**Comment by campionfellin** [comment]
Yeah, maybe we can just put in the contributors guide that you "should" run tests locally before making a PR? I can just take out all the Travis stuff in that case and then update the guide.

**Comment by grant** [comment]
This PR is really good, but we'll have to merge it in chunks.
Can we break out the PR? A PR for each of these; I can merge them more easily:
- format `travis.yml`
- add coverage to Travis
- create the first test (`help` command)
- create the other tests

Let's abandon this PR but use it as reference for the smaller PRs.

**Comment by campionfellin** [comment]
Sounds great, will do. 🤘

**Pull request closed without merging**
