### PR TITLE
Fix OS specific path separator in Apps Script path

### LINKED ISSUE #72: `clasp push` changes the execution order of script files in Apps Script projects
## Expected Behavior
`clasp push` should retain the order of the script files in the Apps Script Editor **not just visually but also in terms of order of execution**. 

## Actual Behavior
`clasp push` re-orders the files so that they are executed in alphabetical order even though visually they retain the expected order in the sidebar of the editor. This bug is hazardous to projects that rely on script files to execute as listed in the Apps Script editor.

## Steps to Reproduce the Problem

  1. Create a stand-alone script project
  2. In that project create 6 script files in sequence and name them Z, Y, X, C, B  and A; each with a `Logger.log()` that logs their respective names.
screenshot_1

 
  3. Create a 7th script file and add the following function:
screenshot_2

  4. Run that function from the menu bar **Run>Run function>runTest**  and then view the logs **View>Logs** and you will get the following:
screenshot_3

 5. Open your terminal and use `clasp clone [PROJECT-FILE-ID]` and then `clasp push` from the command line (project file id omitted from screenshot):
screenshot_4

6. Then run the test function again and then view the logs and you'll see the following:
screenshot_5

**The execution order of the scripts (though visually correct in the editor's sidebar) is changed to run in alphabetical order!**

This bug wreaked havoc on one of my projects before I found it. I would love for clasp to be a part of my development workflow but that won't happen until this issue is resolved.

## Specifications

  - Node version - v6.11.0
  - Clasp Version - 3.10.10
  - OS - Windows

### PR DESCRIPTION
**Pull request by JeanRemiDelteil**
Fix #72

### CODE REVIEW

**Comment by grant** [comment]
Thanks!

**Comment by JeanRemiDelteil** [comment]
Hi @grant any hope for a new stable version ? :)

**Comment by grant** [comment]
@valen22br @JeanRemiDelteil I'm working on 2.0 with `clasp run`. The build I'm working on is very broken. I'm expecting to release next month.
https://github.com/google/clasp/milestone/1

In the meantime, please build clasp from scratch for the latest features.

**Comment by valen22br** [comment]
Thanks, @grant. I appreciate your feedback. In this meantime, I'll be working with the build version.

**Comment by JeanRemiDelteil** [comment]
@grant Really, you could publish a stable version with this fix, with the build from that time (I do not have any idea why you could not use the build from that time).

Having a currently published broken behaviour really impact us when on-boarding new people or when talking of our use of CLASP in a conference (it would be broken) !
We have to edit the installed package manually !

I'm sorry for insisting, if not possible I understand as well ;p

**Comment by grant** [comment]
@JeanRemiDelteil OK, I'll publish a version Friday.

**Comment by JeanRemiDelteil** [comment]
Thank you so much for this !

I'm sorry for insisting, and for not being able to put much effort in the rest of the issues (as CLASP is doing his job very well in all the other aspects :) !)

**Pull request merged**
