### PR TITLE
Lock lines-and-columns to 1.1.6

### PR DESCRIPTION
**Pull request by somethingnew2-0**
[lines-and-columns](https://www.npmjs.com/package/lines-and-columns
) published a breaking change (1.1.7) which broke clasp https://github.com/eventualbuddha/lines-and-columns/pull/199 cc: @eventualbuddha

```
Run clasp login --status
  clasp login --status
  shell: /usr/bin/bash -e {0}
internal/modules/cjs/loader.js:929
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module '/usr/local/lib/node_modules/@google/clasp/node_modules/lines-and-columns/build/index.mjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/node_modules/parse-json/index.js:4:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/local/lib/node_modules/@google/clasp/node_modules/lines-and-columns/package.json'
```

- [ ] `npm run test` succeeds.
- [ ] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Yep, fixing. Sorry about that.

**Comment by eventualbuddha** [comment]
This should be fixed now in 1.1.9. You can either use that or lock to 1.1.6.

**Comment by Dreaming-Codes** [comment]
This solution should not be used, it is better to fix the problem than to continue using an old version.

**Comment by eventualbuddha** [comment]
If you want to move to the latest, just change it to v2.0.2 and use a named import. Nothing else changed.

**Comment by Dreaming-Codes** [comment]
> If you want to move to the latest, just change it to v2.0.2 and use a named import. Nothing else changed.

Actually there is nothing to do here as it is a library that uses lines-and-columns and not google/clasp itself

**Comment by somethingnew2-0** [comment]
Ah, that fixed it. Closing this out.

**Pull request closed without merging**
