### PR TITLE
(Minor) auth.ts uses deprecated http.ServerRequest 

### LINKED ISSUE #477: (Minor) auth.ts uses deprecated http.ServerRequest
## Expected Behavior

in auth.ts, function `authorizeWithLocalhost` has the following code:
```javascript
    server.on('request', (req: http.ServerRequest, resp: http.ServerResponse) => {
[...]
    });
```

According to Node documentation (9.* and up) there is no `http.ServerRequest` class and the `request` event uses the `http.IncomingMessage` instead (cf. https://nodejs.org/docs/latest-v9.x/api/http.html#http_event_request )

Also the below issue indicates that the `http.ServerRequest` is deprecated/gone
https://github.com/nodejs/node-v0.x-archive/issues/3833

Finally, if you update the @types/node package to latest version (I.e. "^10.12.18") you get the following error:
```
Namespace '"http"' has no exported member 'ServerRequest'.
```

I'll issue a PR with proposed update

## Steps to Reproduce the Problem

1.
1.

## Specifications

- Node version (`node -v`): v10.15.0
- Version (`clasp -v`): 1.7.0
- OS (Mac/Linux/Windows): Mac (Mojave latest)

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
Fixes #477

- [ ] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

'npm run test` had errors but they do not seem related to the changes in PR
No need to update README.md

### CODE REVIEW

**Comment by PopGoesTheWza** [comment]
I have a CLA now...

**Comment by takanakahiko** [comment]
https://github.com/google/clasp/pull/478#issue-242228177

In markdown you can check by entering `x` between` [`and`] `.

`- [ ] no checked`
`- [x] checked`

**Comment by PopGoesTheWza** [comment]
@takanakahiko I fixed it. Thanks.

**Comment by grant** [comment]
Thanks!

**Pull request merged**
