### PR TITLE
Refactor clasp pull test

### PR DESCRIPTION
**Pull request by campionfellin**
Improves readability of tests.

Signed-off-by: campionfellin <campionfellin@gmail.com>

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by grant** [comment]
- Can you refactor all tests at once? Combine #598.
- Can you create and/or add an issue that this addresses?

**Comment by campionfellin** [comment]
Yes, I can do two things:

1. Create issue to get coverage >90%
2. Single PR to refactor / finish testing (note: this will be a pretty big PR).

**Comment by grant** [comment]
Looking forward to the large refactoring PR.

**Comment by campionfellin** [comment]
Closing this and #598 in favor of the bigger PR. Work on that is coming along well so far.

**Pull request closed without merging**
