### PR TITLE
fix: do not wait and immediately exit / return opn calls

### PR DESCRIPTION
**Pull request by DanielRuf**
Resolves https://github.com/google/clasp/issues/282

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by DanielRuf** [comment]
> Coverage decreased (-20.6%) to 35.967%

How can I / we increase this again?

**Comment by grant** [comment]
Thanks for the PR @DanielRuf! Don't worry about the coverage, it will be restored when merged to master.

I recently merged a large PR #284, which has a minor conflict with this one. Do you think you can update this PR?

**Comment by DanielRuf** [comment]
I'll rebase and resolve the conflict.

**Comment by DanielRuf** [comment]
Short question: there is another opn call which was not changed. Does it need this change too (I guess not)?

**Comment by grant** [comment]
We should probably `{wait: false}` for all open commands, though I'm not sure.
`open(getWebApplicationURL(deployment), {wait: false});`

**Comment by DanielRuf** [comment]
Would be helpful for me to get some more opinions.

**Comment by DanielRuf** [comment]
> I'll rebase and resolve the conflict.

Done.

**Comment by grant** [comment]
Thanks!

**Comment by grant** [comment]
Note, the master build failure (for 1 version of Node) looks unrelated to this change.
I'll fix that test separately.

**Comment by DanielRuf** [comment]
> Note, the master build failure (for 1 version of Node) looks unrelated to this change.
> I'll fix that test separately.

Thanks. Seems to be some basic assertion that fails.

**Pull request merged**
