### PR TITLE
Exit with non-zero status code

### LINKED ISSUE #159: Exit with an error on non-existing commands
## Expected Behavior

On running a mispelled command, or `help` (instead of the flag) or `list` (unimplemented), the program should print a message and exit with code > 0.

## Actual Behavior

Nothing is printed and the exit code is 0.

This is particularly confusing for `list`, as that was the first command I tried and empty output suggests it can't find any projects.

## Specifications

  - Node version (`node -v`): v10.0.0
  - Version (`npm list -g | grep clasp`): @google/clasp@1.1.5
  - OS (Mac/Linux/Windows): Mac

### PR DESCRIPTION
**Pull request by grant**
Fixes #159.

### CODE REVIEW

**Comment by campionfellin** [comment]
Do we want to use `process.exit(1)` or `logError(...)` ?

Otherwise LGTM

**Comment by grant** [comment]
We're not logging any error message here, so it wouldn't make sense.

**Comment by campionfellin** [comment]
Sorry I must have missed this, so we merged and reverted this? Are we going to just use what was discussed here? https://github.com/google/clasp/issues/159#event-1657362437

**Comment by grant** [comment]
I realized your comment meant put the `exit` in `logError` rather than here. It probably would be better there.

That said, it really doesn't matter and you could argue for both places.

**Comment by campionfellin** [comment]
Up to you if you want to make another PR

**Pull request merged**
