### PR TITLE
sync

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [ ] `npm run test` succeeds.
- [ ] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by grant** [comment]
Please never use the `master` branch for PRs and use a dedicated branch to prevent extra commits.

**Comment by PopGoesTheWza** [comment]
@grant sorry. This was a fumble

**Comment by PopGoesTheWza** [comment]
@grant please bear with me for I failed to see how to make a branch and PR it with only my changes.
Does that requires me to drop my current fork and create a new one?

**Comment by grant** [comment]
No worries.

- Use branches for features (`git checkout -b myfeature`). Always branch from `master`.
- Keep your `PopGoesTheWza/clasp`'s `master` in sync with `google/clasp`'s `master`
  - https://youtu.be/-zvHQXnBO6c?t=234

**Comment by takanakahiko** [comment]
@PopGoesTheWza 
I introduce the procedure to make a PR.

First-time steps

1. Fork on GitHub
2. `$ git clone takanakahiko/clasp && cd clasp`
3. `$ git remote add upstream git@github.com:google/clasp.git`

Steps to take when creating a PR each time

4. (in master branch) `$ git fetch upstream`
5. `$ git merge upstream/master`
6. `$ git checkout -b my-new-feature`
7. Change source code.
8. `$ git commit -am 'Add some feature'`
9. `$ git push origin my-new-feature`
10. Submit a pull request :D

How to follow when the google / clasp master branch is updated as you work

1. (in `my-new-feature` branch) `$ git fetch upstream`
2. `$ git merge upstream/master`

**Comment by PopGoesTheWza** [comment]
@takanakahiko thanks!

Will you PR this to <https://github.com/google/clasp/blob/master/docs/develop.md> ?

**Comment by takanakahiko** [comment]
@PopGoesTheWza Your welcome!
But, this is a usage of GitHub, so it is inappropriate to write it as a document in the repository, which may cause the document to grow.
I would like to consult with the maintainer if there is an opportunity.

**Pull request closed without merging**
