### PR TITLE
(WIP) Issue 626 - default `.claspignore`

### LINKED ISSUE #626: clasp push: UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.claspignore'
## Expected Behavior

`clasp push` works

## Actual Behavior

`clasp push` without `.claspignore` fails.
```
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.claspignore' 
```

This is probably broken due to a PR that modified `.claspignore`.

I can't publish clasp until this is fixed.

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
Fixes #626 

- [ ] `npm run test` succeeds.
- [ ] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by grant** [comment]
Let's be focused when we create PRs.
Only solve the issue, don't make any other changes.

**Comment by PopGoesTheWza** [comment]
I am focused, trust me. But since I am to switch while in the middle of another PR, I prefer to take the opportunity of minor fixes (TODOs, improved typings...) :-P

**Comment by grant** [comment]
Thanks for the PR. Please make the PR only include changes in these files:

```
src/dotfile.ts 
tests/commands/push.ts
```

Move the other changes to a different PR.

**Comment by PopGoesTheWza** [comment]
@grant I am not that fluent in Git, sorry. I have no idea how to move some changed files to another branch nor how to 'revert' part of the commits.

**Comment by grant** [comment]
No problem. I recommend always syncing with the latest master branch and working from there.

This may be useful:

https://medium.com/sweetmeat/how-to-keep-a-downstream-git-repository-current-with-upstream-repository-changes-10b76fad6d97

**Pull request closed without merging**
